-- Seed sample therapists based on sampleTherapists in app/page.tsx
-- Safe to run multiple times thanks to ON CONFLICT(id) DO UPDATE

INSERT INTO "therapists" (
  "id",
  "name",
  "credentials",
  "specialties",
  "rating",
  "reviewCount",
  "pricePerSession",
  "location",
  "nextAvailable",
  "avatar",
  "acceptsInsurance",
  "sessionTypes",
  "languages",
  "yearsExperience",
  "timezone",
  "updated_at"
) VALUES
  (
    'seed-1',
    'Lic. Sofía Martínez',
    'Licenciada en Psicología, Mat. N° 23456 (Colegio de Psicólogos CABA)',
    ARRAY['Ansiedad','Depresión','Trauma','Trastorno por Estrés Postraumático (TEPT)']::text[],
    4.9,
    127,
    150,
    'Palermo, Ciudad de Buenos Aires',
    'Hoy 15:00',
    '/professional-woman-therapist.png',
    true,
    ARRAY['Online']::text[],
    ARRAY['Español','Inglés']::text[],
    12,
    'America/Argentina/Buenos_Aires',
    now()
  ),
  (
    'seed-2',
    'Lic. Martín Chen',
    'Licenciado en Psicología, Especialista en Terapia Familiar, Mat. N° 34567 (Colegio de Psicólogos PBA)',
    ARRAY['Terapia de pareja','Terapia familiar','Comunicación']::text[],
    4.8,
    89,
    180,
    'San Isidro, Provincia de Buenos Aires',
    'Mañana 10:00',
    '/professional-asian-male-therapist.png',
    false,
    ARRAY['Presencial']::text[],
    ARRAY['Español','Portugués']::text[],
    8,
    'Europe/Madrid',
    now()
  ),
  (
    'seed-3',
    'Dra. Emilia Rodríguez',
    'Doctora en Psicología, Mat. N° 45678 (Colegio de Psicólogos de Córdoba)',
    ARRAY['TDAH','Autismo','Terapia infantil','Problemas conductuales']::text[],
    4.9,
    156,
    120,
    'Córdoba, Córdoba',
    'Lunes 14:00',
    '/professional-latina-female-therapist.png',
    true,
    ARRAY['Online']::text[],
    ARRAY['Español','Inglés']::text[],
    15,
    'America/New_York',
    now()
  ),
  (
    'seed-4',
    'Lic. Juan Pérez',
    'Psicólogo Clínico, Mat. N° 56789 (Colegio de Psicólogos de Rosario)',
    ARRAY['Adicciones','Abuso de sustancias','Manejo de la ira']::text[],
    4.7,
    73,
    140,
    'Rosario, Santa Fe',
    'Miércoles 16:00',
    '/professional-black-male-therapist.png',
    true,
    ARRAY['Online','Presencial']::text[],
    ARRAY['Español']::text[],
    10,
    'America/Argentina/Buenos_Aires',
    now()
  ),
  (
    'seed-5',
    'Lic. Lucía Gómez',
    'Licenciada en Psicología, Mat. N° 67890 (Colegio de Psicólogos de La Plata)',
    ARRAY['Trastornos alimentarios','Imagen corporal','Autoestima']::text[],
    4.8,
    94,
    160,
    'Mar del Plata, Provincia de Buenos Aires',
    'Viernes 11:00',
    '/professional-blonde-female-therapist.png',
    false,
    ARRAY['Online','Presencial']::text[],
    ARRAY['Español']::text[],
    9,
    'America/Argentina/Buenos_Aires',
    now()
  ),
  (
    'seed-6',
    'Lic. Diego Kim',
    'Licenciado en Psicología, Mat. N° 78901 (Colegio de Psicólogos CABA)',
    ARRAY['Ansiedad','TOC','Trastornos de pánico','Mindfulness']::text[],
    4.9,
    112,
    135,
    'Belgrano, Ciudad de Buenos Aires',
    'Hoy 18:00',
    '/professional-korean-male-therapist.png',
    true,
    ARRAY['Online','Presencial']::text[],
    ARRAY['Español','Inglés']::text[],
    7,
    'America/Argentina/Buenos_Aires',
    now()
  )
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "credentials" = EXCLUDED."credentials",
  "specialties" = EXCLUDED."specialties",
  "rating" = EXCLUDED."rating",
  "reviewCount" = EXCLUDED."reviewCount",
  "pricePerSession" = EXCLUDED."pricePerSession",
  "location" = EXCLUDED."location",
  "nextAvailable" = EXCLUDED."nextAvailable",
  "avatar" = EXCLUDED."avatar",
  "acceptsInsurance" = EXCLUDED."acceptsInsurance",
  "sessionTypes" = EXCLUDED."sessionTypes",
  "languages" = EXCLUDED."languages",
  "yearsExperience" = EXCLUDED."yearsExperience",
  "updated_at" = now();

